# Generated by Django 5.1.4 on 2025-01-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0005_alter_users_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
