@url = http://localhost:8000

### signup
POST {{url}}/auth_service/signup/ HTTP/1.1
Content-Type: application/json

{
    "first_name" : "Beste",
    "last_name" : "Gürsoy",
    "password" : "123456",
    "email" : "bestegursoyy52@hotmail.com"
}


### signin
POST {{url}}/auth_service/signin/ HTTP/1.1
Content-Type: application/json

{
    "email" : "bestegursoy52@hotmail.com",
    "password" : "123456"
}


### Reset password
PUT {{url}}/auth_service/reset_password/ HTTP/1.1
Content-Type: application/json

{
    "email": "bestegursoy52@hotmail.com",
    "password": "987654",
    "confirm_password": "987654"
}
