@url = http://localhost:8000

### signup
POST {{url}}/auth_service/signup/ HTTP/1.1
Content-Type: application/json

{
    "username" : "esdasdsfşsrsdk55e",
    "first_name" : "Beste",
    "last_name" : "Gürsoy",
    "password" : "123456",
    "email" : "55@gmail.com"
}


### signin
POST {{url}}/auth_service/signin/ HTTP/1.1
Content-Type: application/json

{
    "email" : "55@gmail.com",
    "password" : "123456"
}