# Generated by Django 5.1.4 on 2025-01-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='reciever_mail',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
    ]
