# Generated by Django 5.1.4 on 2025-01-14 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0003_users_is_active'),
        ('notes_service', '0002_notes_reciever_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='reciever_mail',
        ),
        migrations.AddField(
            model_name='notes',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='auth_service.users'),
        ),
    ]
