# Generated by Django 5.1.4 on 2025-01-06 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_service', '0003_users_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='dailynotes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_service.users')),
            ],
        ),
    ]
