# Generated by Django 5.1.4 on 2025-01-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailynotes_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailynotes',
            name='mission_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
