# Generated by Django 5.1.4 on 2025-01-09 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailynotes_service', '0002_dailynotes_mission_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailynotes',
            name='owner_mail',
        ),
    ]
