# Generated by Django 5.1.4 on 2025-01-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailynotes_service', '0003_remove_dailynotes_owner_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailynotes',
            name='reciever_mail',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
    ]
